defaults: &netcore
  docker:
    - image: microsoft/aspnetcore-build:2.0
      environment:
        VERSION_PREFIX: "1.0"
  working_directory: ~/app

version: 2
jobs:
  build:
    <<: *netcore
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            export VERSION="${VERSION_PREFIX}.${CIRCLE_BUILD_NUM}"
            dotnet pack -c Release -o ../../artifacts src/MassTransit.RabbitMq.Extensions.Hosting /p:PackageVersion=$VERSION /p:Version=$VERSION  /p:AssemblyVersion=$VERSION
      - persist_to_workspace:
          root: ~/app
          paths: .

  publish:
    <<: *netcore
    steps:
      - attach_workspace:
          at: ~/app
      - run: dotnet nuget push artifacts/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master